[package]
name = "rustnet"
version = "0.3.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
arboard = "3.5"
crossterm = "0.29"
crossbeam = "0.8"
dashmap = "6.1"
dns-lookup = "2.0"
log = "0.4"
num_cpus = "1.17"
pcap = "2.3.0"
pnet_datalink = "0.35"
clap = { version = "4.5", features = ["derive"] }
simple-logging = "2.0"
simplelog = "0.12"
chrono = "0.4"
ratatui = { version = "0.29", features = ["all-widgets"] }
ring = "0.17"
aes = "0.8"

[target.'cfg(target_os = "linux")'.dependencies]
procfs = "0.16"
