[package]
name = "rustnet"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
arboard = "3.5"
crossterm = "0.29"
dns-lookup = "2.0"
log = "0.4"
pcap = "2.2"
pnet_datalink = "0.35"
clap = { version = "4.5", features = ["derive"] }
simple-logging = "2.0.2"
simplelog = "0.12"
chrono = "0.4"
ratatui = { version = "0.29.0", features = ["all-widgets"] }

[target.'cfg(target_os = "linux")'.dependencies]
procfs = "0.16"
